repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/python-poetry/poetry
    rev: "1.7.0"
    hooks:
      - id: poetry-check
-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black
    -   id: black-jupyter

-   repo: https://github.com/astral-sh/ruff-pre-commit
     # Ruff version.
    rev: v0.1.9
    hooks:
        # Run the linter.
        - id: ruff
          types_or: [ python, pyi, jupyter ]
          args: [ --fix ]


-   repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
    -   id: nbstripout
ci:
    autofix_prs: true
    autoupdate_schedule: "weekly"
