name: Tests
on: [push, pull_request, workflow_call]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: "poetry"

      - name: Install packages
        run: poetry install

      - name: Run tests
        run: poetry run pytest
