#
name: Tests
on:
  push:
    branches-ignore:
      - main # Ignore main branch, deploy workflow will call it
  pull_request:
  workflow_call:

env:
  ENV_NAME: conda-env

jobs:
  test-project:
    name: Run Tests on Python 3.9
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          activate-environment: ${{ env.ENV_NAME }}
          environment-file: conda-linux-64.lock

      - name: Run tests
        run: |
          conda activate $ENV_NAME
          conda env info
          poetry run pytest
#
